sudo: false

language: ruby

rvm:
  - 2.2.7
  - 2.3.4
  - 2.4.1

gemfile:
  - gemfiles/active_record_50.gemfile
  - gemfiles/active_record_42.gemfile
  - gemfiles/active_record_41.gemfile
  - gemfiles/active_record_edge.gemfile

script:
  - bundle exec rake spec
  - bundle exec rubocop --display-cop-names

cache: bundler

matrix:
  allow_failures:
    - gemfile: gemfiles/active_record_edge.gemfile
  fast_finish: true
